/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                primary: {
                    50: '#fefce8',
                    100: '#fef3c7',
                    200: '#fde68a',
                    300: '#fcd34d',
                    400: '#fbbf24',
                    500: '#f59e0b',
                    600: '#d97706',
                    700: '#b45309',
                    800: '#92400e',
                    900: '#78350f',
                    950: '#451a03',
                },
                secondary: {
                    50: '#fff7ed',
                    100: '#ffedd5',
                    200: '#fed7aa',
                    300: '#fdba74',
                    400: '#fb923c',
                    500: '#f97316',
                    600: '#ea580c',
                    700: '#c2410c',
                    800: '#9a3412',
                    900: '#7c2d12',
                    950: '#431407',
                },
                accent: {
                    yellow: '#fbbf24',
                    orange: '#f97316',
                    'light-yellow': '#fef3c7',
                    'light-orange': '#fed7aa',
                    'dark-yellow': '#d97706',
                    'dark-orange': '#ea580c',
                },
                success: {
                    50: '#f0fdf4',
                    100: '#dcfce7',
                    200: '#bbf7d0',
                    300: '#86efac',
                    400: '#4ade80',
                    500: '#22c55e',
                    600: '#16a34a',
                    700: '#15803d',
                    800: '#166534',
                    900: '#14532d',
                    950: '#052e16',
                },
                error: {
                    50: '#fef2f2',
                    100: '#fee2e2',
                    200: '#fecaca',
                    300: '#fca5a5',
                    400: '#f87171',
                    500: '#ef4444',
                    600: '#dc2626',
                    700: '#b91c1c',
                    800: '#991b1b',
                    900: '#7f1d1d',
                    950: '#450a0a',
                },
                warning: {
                    50: '#fffbeb',
                    100: '#fef3c7',
                    200: '#fde68a',
                    300: '#fcd34d',
                    400: '#fbbf24',
                    500: '#f59e0b',
                    600: '#d97706',
                    700: '#b45309',
                    800: '#92400e',
                    900: '#78350f',
                    950: '#451a03',
                },
                neutral: {
                    50: '#fafafa',
                    100: '#f5f5f5',
                    200: '#e5e5e5',
                    300: '#d4d4d4',
                    400: '#a3a3a3',
                    500: '#737373',
                    600: '#525252',
                    700: '#404040',
                    800: '#262626',
                    900: '#171717',
                    950: '#0a0a0a',
                }
            },
            fontFamily: {
                sans: [
                    'Inter',
                    'SF Pro Display',
                    '-apple-system',
                    'BlinkMacSystemFont',
                    'Segoe UI',
                    'Roboto',
                    'Helvetica Neue',
                    'Arial',
                    'sans-serif'
                ],
                mono: [
                    'SF Mono',
                    'Monaco',
                    'Inconsolata',
                    'Roboto Mono',
                    'source-code-pro',
                    'Menlo',
                    'monospace'
                ],
            },
            fontSize: {
                'xs': ['0.75rem', { lineHeight: '1rem' }],
                'sm': ['0.875rem', { lineHeight: '1.25rem' }],
                'base': ['1rem', { lineHeight: '1.5rem' }],
                'lg': ['1.125rem', { lineHeight: '1.75rem' }],
                'xl': ['1.25rem', { lineHeight: '1.75rem' }],
                '2xl': ['1.5rem', { lineHeight: '2rem' }],
                '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
                '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
                '5xl': ['3rem', { lineHeight: '1' }],
                '6xl': ['3.75rem', { lineHeight: '1' }],
                '7xl': ['4.5rem', { lineHeight: '1' }],
                '8xl': ['6rem', { lineHeight: '1' }],
                '9xl': ['8rem', { lineHeight: '1' }],
            },
            backgroundImage: {
                'gradient-main': 'linear-gradient(135deg, #fef3c7 0%, #fed7aa 50%, #ffffff 100%)',
                'gradient-primary': 'linear-gradient(45deg, #fbbf24, #f97316)',
                'gradient-hover': 'linear-gradient(45deg, #d97706, #ea580c)',
                'gradient-radial': 'radial-gradient(ellipse at center, var(--tw-gradient-stops))',
                'gradient-radial-at-t': 'radial-gradient(ellipse at top, var(--tw-gradient-stops))',
                'gradient-radial-at-b': 'radial-gradient(ellipse at bottom, var(--tw-gradient-stops))',
                'gradient-radial-at-l': 'radial-gradient(ellipse at left, var(--tw-gradient-stops))',
                'gradient-radial-at-r': 'radial-gradient(ellipse at right, var(--tw-gradient-stops))',
                'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
                'mesh-gradient': 'linear-gradient(135deg, rgba(251, 191, 36, 0.1) 0%, rgba(249, 115, 22, 0.1) 25%, rgba(251, 191, 36, 0.1) 50%, rgba(249, 115, 22, 0.1) 75%, rgba(251, 191, 36, 0.1) 100%)',
                'noise': "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.65' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E\")",
                'glass': 'linear-gradient(135deg, rgba(255, 255, 255, 0.1), rgba(255, 255, 255, 0))',
                'glass-dark': 'linear-gradient(135deg, rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0))',
            },
        },
        animation: {
            'fade-in': 'fadeIn 0.6s ease-out',
            'fade-in-up': 'fadeInUp 0.6s ease-out',
            'fade-in-down': 'fadeInDown 0.6s ease-out',
            'fade-in-left': 'fadeInLeft 0.6s ease-out',
            'fade-in-right': 'fadeInRight 0.6s ease-out',
            'slide-in': 'slideIn 0.5s ease-out',
            'slide-in-up': 'slideInUp 0.5s ease-out',
            'slide-in-down': 'slideInDown 0.5s ease-out',
            'slide-up': 'slideUp 0.5s ease-out',
            'slide-down': 'slideDown 0.5s ease-out',
            'bounce-subtle': 'bounceSubtle 2s infinite',
            'bounce-slow': 'bounceSubtle 3s infinite',
            'pulse-slow': 'pulse 3s infinite',
            'pulse-faster': 'pulse 1s infinite',
            'float': 'float 6s ease-in-out infinite',
            'float-slow': 'float 8s ease-in-out infinite',
            'float-fast': 'float 4s ease-in-out infinite',
            'glow': 'glow 2s ease-in-out infinite alternate',
            'glow-pulse': 'glowPulse 2s ease-in-out infinite',
            'scale-in': 'scaleIn 0.3s ease-out',
            'scale-up': 'scaleUp 0.2s ease-out',
            'shimmer': 'shimmer 2s linear infinite',
            'shimmer-slow': 'shimmer 3s linear infinite',
            'spin-slow': 'spin 3s linear infinite',
            'ping-slow': 'ping 3s cubic-bezier(0, 0, 0.2, 1) infinite',
            'wobble': 'wobble 1s ease-in-out',
            'shake': 'shake 0.5s ease-in-out',
            'rubber-band': 'rubberBand 0.8s ease-in-out',
            'zoom-in': 'zoomIn 0.3s ease-out',
            'zoom-out': 'zoomOut 0.3s ease-out',
            'flip': 'flip 0.6s ease-in-out',
            'rotate-in': 'rotateIn 0.5s ease-out',
            'slide-reveal': 'slideReveal 0.8s ease-out',
            'typewriter': 'typewriter 3s steps(40) 1s forwards',
            'gradient-x': 'gradientX 3s ease infinite',
            'gradient-y': 'gradientY 3s ease infinite',
            'gradient-xy': 'gradientXY 3s ease infinite',
            'morphing': 'morphing 8s ease-in-out infinite',
            'spotlight': 'spotlight 2s ease-in-out infinite alternate',
        },
        keyframes: {
            fadeIn: {
                '0%': { opacity: '0', transform: 'translateY(20px)' },
                '100%': { opacity: '1', transform: 'translateY(0)' },
            },
            fadeInUp: {
                '0%': { opacity: '0', transform: 'translateY(30px)' },
                '100%': { opacity: '1', transform: 'translateY(0)' },
            },
            fadeInDown: {
                '0%': { opacity: '0', transform: 'translateY(-30px)' },
                '100%': { opacity: '1', transform: 'translateY(0)' },
            },
            fadeInLeft: {
                '0%': { opacity: '0', transform: 'translateX(-30px)' },
                '100%': { opacity: '1', transform: 'translateX(0)' },
            },
            fadeInRight: {
                '0%': { opacity: '0', transform: 'translateX(30px)' },
                '100%': { opacity: '1', transform: 'translateX(0)' },
            },
            slideIn: {
                '0%': { opacity: '0', transform: 'translateX(-20px)' },
                '100%': { opacity: '1', transform: 'translateX(0)' },
            },
            slideInUp: {
                '0%': { opacity: '0', transform: 'translateY(100%)' },
                '100%': { opacity: '1', transform: 'translateY(0)' },
            },
            slideInDown: {
                '0%': { opacity: '0', transform: 'translateY(-100%)' },
                '100%': { opacity: '1', transform: 'translateY(0)' },
            },
            slideUp: {
                '0%': { opacity: '0', transform: 'translateY(30px)' },
                '100%': { opacity: '1', transform: 'translateY(0)' },
            },
            slideDown: {
                '0%': { opacity: '0', transform: 'translateY(-30px)' },
                '100%': { opacity: '1', transform: 'translateY(0)' },
            },
            bounceSubtle: {
                '0%, 100%': { transform: 'translateY(0)' },
                '50%': { transform: 'translateY(-5px)' },
            },
            float: {
                '0%, 100%': { transform: 'translateY(0px)' },
                '50%': { transform: 'translateY(-10px)' },
            },
            glow: {
                '0%': { boxShadow: '0 0 5px rgba(251, 191, 36, 0.2), 0 0 10px rgba(251, 191, 36, 0.2), 0 0 15px rgba(251, 191, 36, 0.2)' },
                '100%': { boxShadow: '0 0 10px rgba(249, 115, 22, 0.4), 0 0 20px rgba(249, 115, 22, 0.4), 0 0 30px rgba(249, 115, 22, 0.4)' },
            },
            glowPulse: {
                '0%, 100%': {
                    boxShadow: '0 0 5px rgba(251, 191, 36, 0.3), 0 0 10px rgba(251, 191, 36, 0.2), 0 0 15px rgba(251, 191, 36, 0.1)',
                    filter: 'brightness(1)'
                },
                '50%': {
                    boxShadow: '0 0 15px rgba(249, 115, 22, 0.5), 0 0 25px rgba(249, 115, 22, 0.3), 0 0 35px rgba(249, 115, 22, 0.2)',
                    filter: 'brightness(1.1)'
                },
            },
            scaleIn: {
                '0%': { opacity: '0', transform: 'scale(0.9)' },
                '100%': { opacity: '1', transform: 'scale(1)' },
            },
            scaleUp: {
                '0%': { transform: 'scale(1)' },
                '100%': { transform: 'scale(1.05)' },
            },
            shimmer: {
                '0%': { transform: 'translateX(-100%)' },
                '100%': { transform: 'translateX(100%)' },
            },
            wobble: {
                '0%': { transform: 'translateX(0%)' },
                '15%': { transform: 'translateX(-25%) rotate(-5deg)' },
                '30%': { transform: 'translateX(20%) rotate(3deg)' },
                '45%': { transform: 'translateX(-15%) rotate(-3deg)' },
                '60%': { transform: 'translateX(10%) rotate(2deg)' },
                '75%': { transform: 'translateX(-5%) rotate(-1deg)' },
                '100%': { transform: 'translateX(0%)' },
            },
            shake: {
                '0%, 100%': { transform: 'translateX(0)' },
                '10%, 30%, 50%, 70%, 90%': { transform: 'translateX(-10px)' },
                '20%, 40%, 60%, 80%': { transform: 'translateX(10px)' },
            },
            rubberBand: {
                '0%': { transform: 'scale(1)' },
                '30%': { transform: 'scaleX(1.25) scaleY(0.75)' },
                '40%': { transform: 'scaleX(0.75) scaleY(1.25)' },
                '50%': { transform: 'scaleX(1.15) scaleY(0.85)' },
                '65%': { transform: 'scaleX(0.95) scaleY(1.05)' },
                '75%': { transform: 'scaleX(1.05) scaleY(0.95)' },
                '100%': { transform: 'scale(1)' },
            },
            zoomIn: {
                '0%': { opacity: '0', transform: 'scale(0.3)' },
                '50%': { opacity: '1' },
                '100%': { opacity: '1', transform: 'scale(1)' },
            },
            zoomOut: {
                '0%': { opacity: '1', transform: 'scale(1)' },
                '50%': { opacity: '0', transform: 'scale(3)' },
                '100%': { opacity: '0' },
            },
            flip: {
                '0%': { transform: 'perspective(400px) rotateY(0)' },
                '40%': { transform: 'perspective(400px) translateZ(150px) rotateY(-190deg)' },
                '50%': { transform: 'perspective(400px) translateZ(150px) rotateY(-190deg)' },
                '80%': { transform: 'perspective(400px) scale(0.95)' },
                '100%': { transform: 'perspective(400px)' },
            },
            rotateIn: {
                '0%': { opacity: '0', transform: 'rotate(-200deg)' },
                '100%': { opacity: '1', transform: 'rotate(0deg)' },
            },
            slideReveal: {
                '0%': { transform: 'translateX(-100%)', opacity: '0' },
                '50%': { opacity: '0.5' },
                '100%': { transform: 'translateX(0)', opacity: '1' },
            },
            typewriter: {
                '0%': { width: '0' },
                '100%': { width: '100%' },
            },
            gradientX: {
                '0%, 100%': { backgroundPosition: '0% 50%' },
                '50%': { backgroundPosition: '100% 50%' },
            },
            gradientY: {
                '0%, 100%': { backgroundPosition: '50% 0%' },
                '50%': { backgroundPosition: '50% 100%' },
            },
            gradientXY: {
                '0%, 100%': { backgroundPosition: '0% 0%' },
                '25%': { backgroundPosition: '100% 0%' },
                '50%': { backgroundPosition: '100% 100%' },
                '75%': { backgroundPosition: '0% 100%' },
            },
            morphing: {
                '0%, 100%': { borderRadius: '60% 40% 30% 70%/60% 30% 70% 40%' },
                '50%': { borderRadius: '30% 60% 70% 40%/50% 60% 30% 60%' },
            },
            spotlight: {
                '0%': { transform: 'scale(0.5)', filter: 'brightness(0.5)' },
                '100%': { transform: 'scale(1)', filter: 'brightness(1)' },
            },
        },
        backdropBlur: {
            xs: '2px',
            sm: '4px',
            md: '8px',
            lg: '12px',
            xl: '16px',
            '2xl': '24px',
            '3xl': '32px',
        },
        backdropFilter: {
            'none': 'none',
            'blur': 'blur(8px)',
        },
        boxShadow: {
            'soft': '0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 10px 20px -2px rgba(0, 0, 0, 0.04)',
            'medium': '0 4px 20px -2px rgba(0, 0, 0, 0.1), 0 2px 8px -2px rgba(0, 0, 0, 0.04)',
            'strong': '0 10px 40px -5px rgba(0, 0, 0, 0.1), 0 4px 25px -5px rgba(0, 0, 0, 0.05)',
            'extra-strong': '0 15px 50px -8px rgba(0, 0, 0, 0.15), 0 8px 30px -5px rgba(0, 0, 0, 0.08)',
            'glow': '0 0 20px rgba(251, 191, 36, 0.3)',
            'glow-sm': '0 0 10px rgba(251, 191, 36, 0.2)',
            'glow-lg': '0 0 30px rgba(251, 191, 36, 0.4)',
            'glow-orange': '0 0 20px rgba(249, 115, 22, 0.3)',
            'glow-orange-sm': '0 0 10px rgba(249, 115, 22, 0.2)',
            'glow-orange-lg': '0 0 30px rgba(249, 115, 22, 0.4)',
            'glow-success': '0 0 20px rgba(34, 197, 94, 0.3)',
            'glow-error': '0 0 20px rgba(239, 68, 68, 0.3)',
            'inner-soft': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
            'inner-medium': 'inset 0 4px 8px 0 rgba(0, 0, 0, 0.1)',
            'glass': '0 8px 32px 0 rgba(31, 38, 135, 0.37)',
            'glass-dark': '0 8px 32px 0 rgba(0, 0, 0, 0.37)',
            'elevated': '0 20px 40px -8px rgba(0, 0, 0, 0.12), 0 8px 16px -4px rgba(0, 0, 0, 0.08)',
            'floating': '0 10px 30px -5px rgba(0, 0, 0, 0.1), 0 0 20px rgba(251, 191, 36, 0.1)',
        },
        spacing: {
            '18': '4.5rem',
            '88': '22rem',
            '128': '32rem',
            '144': '36rem',
            '160': '40rem',
            '176': '44rem',
            '192': '48rem',
            '208': '52rem',
            '224': '56rem',
            '240': '60rem',
        },
        blur: {
            xs: '2px',
            '4xl': '72px',
            '5xl': '96px',
            '6xl': '128px',
        },
        borderRadius: {
            '4xl': '2rem',
            '5xl': '2.5rem',
            '6xl': '3rem',
        },
        transitionDuration: {
            '400': '400ms',
            '600': '600ms',
            '800': '800ms',
            '900': '900ms',
            '1200': '1200ms',
            '1500': '1500ms',
            '2000': '2000ms',
        },
        transitionDelay: {
            '400': '400ms',
            '600': '600ms',
            '800': '800ms',
            '900': '900ms',
            '1200': '1200ms',
        },
        scale: {
            '102': '1.02',
            '103': '1.03',
            '98': '0.98',
            '97': '0.97',
        },
        zIndex: {
            '60': '60',
            '70': '70',
            '80': '80',
            '90': '90',
            '100': '100',
        },
    },
},
plugins: [],
}